### ISSUE TITLE
Bylaws: Create provision for ballots to be withdrawn before voting period is complete

### ISSUE THREAD

**Issue by aarongable** [cabforum/forum#17]
Recently, two ballots have been found to have structural issues (e.g. malformed effective-by dates) during the voting period rather than during the discussion period. Because there is no mechanism for a ballot to be withdrawn, this means that ballot authors must wait for the voting period to close (and rely on the understanding of other CABF members to ensure that the ballot is voted down) before they can submit a new fixed-up version of the ballot.

The Bylaws could provide a mechanism for authors and/or endorsers to withdraw ballots that are found to be malformed during the voting period, allowing for quicker turnaround and less "paperwork" when such a situation arises.

**Comment by dzacharo** [comment]
LGTM

**Comment by dzacharo** [comment]
Fixed in section 2.3 (4) of Bylaws version 2.5.
