### ISSUE TITLE
Bylaws: Review requirements for publication of minutes and ballots for WGs

### ISSUE THREAD

**Issue by castillar** [cabforum/forum#21]
At the moment, §5.2 of the Bylaws includes requirements for posting minutes and ballots to mailers, but the requirement for minutes and ballots is _only scoped to those from the Forum_:

> The following materials shall be posted to the Forum Public Mail List or Public Web
Site:
> 1. Draft and final agendas for CWG meetings, Forum Meetings and Forum
Teleconferences (including any sub-groups or committees).
> 2. Final minutes of Forum Meetings and Forum Teleconferences (including minutes
of any sub- groups or committees).
> 3. Messages formally proposing a Forum ballot (including ballots to establish,
extend, modify, or terminate CWGs), individual votes, vote and quorum counts,
and messages announcing ballot outcomes and voting breakdowns.
> 4. Initial and final drafts of Forum requirements, guidelines, and recommendations
after the drafter has had an opportunity to receive and respond to initial Member
comments.
> 5. Initial and final drafts of CWG charter documents, guidelines, and
recommendations after the drafter has had an opportunity to receive and
respond to initial Working Group member comments.

While there is a requirement for CWGs to follow these requirements, the explicit scoping in (2), (3), and (4) to "Forum" materials could be interpreted as waiving this requirement for publishing, e.g., a ballot or final document passed by a Working Group.

We should update these requirements to specify that all Working Groups must publish the results of ballots, final guidelines, and meeting minutes to their designated areas on cabforum.org and the appropriate mailers.

**Comment by dzacharo** [comment]
Fixed
