### ISSUE TITLE
Clarify the Effective Date of Ballots

### ISSUE THREAD

**Issue by wthayer** [cabforum/forum#22]
Ballots technically become effective when the IP review period ends. Bylaws section 2.4 (8) is somewhat confusing because it implies that the ballot becomes effective when the Chair send the notification, or even whenever the Chair chooses. The Bylaws should be clarified to clearly state that a ballot becomes effective at the end of the review period or at some other explicit time, e.g. 45 days after the end of voting.

**Comment by dzacharo** [comment]
Fixed in Bylaws version 2.5.
