### ISSUE TITLE
Increase discussion period time limit

### ISSUE THREAD

**Issue by timfromdigicert** [cabforum/forum#25]
The bylaws currently cause ballots to expire after three weeks of discussion.  This was intended to prevent abandoned ballots that could suddenly come up for a vote, potentially years later.

However, with meetings only happening every two weeks, with occasional vacations and holidays and with some ballots requiring some complex thought and discussion, it isn't uncommon for a live ballot to go more than three weeks without an update.  While this can be worked around with "no-op" updates that just refresh the dates, that doesn't work well with holidays and vacations.  In summary, having the expiration period be only three weeks has historically caused more work and problems than it has solved.

It seems more reasonable if the automatic expiration was more like 60 or 90 days.  A ballot author can still end the discussion period by withdrawing the ballot earlier if they no longer want to move forward.  This would just remove the unhelpful sword of damocles that is currently hovering above head of ballot authors and replace it with their judgement.

**Comment by BenWilson-Mozilla** [comment]
I'm going to propose 35 days as a compromise and so we can close this.

**Comment by dzacharo** [comment]
Ben agreed to make it 90 days.

**Comment by dzacharo** [comment]
This issue has been addressed in Bylaws version 2.5.
