### ISSUE TITLE
Infra: Send weekly summaries of GitHub activity

### ISSUE THREAD

**Issue by sleevi** [cabforum/forum#5]
With the possibility of activity happening both on the mailing list and on GitHub (via issues and pull requests), it would be good to have a weekly summary of activity sent to each respective WG's mailing lists, to make sure folks are aware, even if they're not subscribed to changes.

For example, the IETF uses https://github.com/ietf-github-services/activity-summary , which itself just configuration for [scripts developed for the W3C](https://github.com/dontcallmedom/github-notify-ml)

To do this, we need to:

- [X] Set up an email account authorized to send mail
  - infra-bot was set up for this, but there's been enough issues with the configuration that this probably needs to be revisited.
- [ ] Configure the mailman lists to allow posting from that email account
- [X] Configure GitHub Secrets for the repository with the SMTP password
  - This assumes we'll configure it in the https://github.com/cabforum/forum repository, so that Infrastructure WG activity is notified to the Forum at large. However, we can also consider establishing a separate repository that only dispatches tooling-related summaries to the Infrastructure WG
  - Currently set up in the https://github.com/cabforum/servercert repository, but the discussion had been that we should set up a new repository just for the mailing config and action (that is, rather than per-CWG, do a cabforum/mailer repository that has both the secrets and the list configuration)

**Comment by CBonnell** [comment]
I believe this is now complete. The weekly Activity Summaries have been configured to be sent every Sunday AM and the initial run this morning successfully sent the first weekly digest to the S/MIME WG public list.

Additional configuration items (such as monitoring more repos, sending to additional mailing lists) can be handled in separate issues. I think this issue can be closed.

**Comment by BenWilson-Mozilla** [comment]
This is definitely occurring already.
