### ISSUE TITLE
Infra: Update README.md across the CA/B Forum Repositories

### ISSUE THREAD

**Issue by sleevi** [cabforum/forum#6]
We should add [README.md](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes#about-readmes) details to each of the repositories, dealing the Chartered Working Group activity and the process for getting involved.

**Comment by castillar** [comment]
Re-opening issue until forum/code-signing gets a README. :)

**Comment by castillar** [comment]
Closing now that everything has a README in place!
